name: Scheduled Lead Report

on:
  schedule:
    # Runs at 11:00, 14:00, 16:00, and 18:00 IST
    - cron: '30 5,8,10,12 * * *'  # UTC times (IST-5:30)
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary pandas tabulate
    
    - name: Run report script
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        echo "Checking environment variables (sanitized):"
        echo "DB_HOST is set: ${{ secrets.DB_HOST != '' }}"
        echo "DB_PORT is set: ${{ secrets.DB_PORT != '' }}"
        echo "DB_NAME is set: ${{ secrets.DB_NAME != '' }}"
        echo "DB_USER is set: ${{ secrets.DB_USER != '' }}"
        python main.py 