name: Scheduled Lead Report

on:
  schedule:
    # Runs at 11:00, 14:00, 16:00, and 18:00 IST (UTC+5:30)
    - cron: '30 5,8,10,12 * * *'  # UTC times: 05:30, 08:30, 10:30, 12:30
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify environment variables
      run: |
        echo "DB_HOST: $DB_HOST"
        echo "DB_NAME: $DB_NAME"
        echo "EMAIL_SENDER: $EMAIL_SENDER"

    - name: Run report script
      run: python main.py
      env:
        # Explicitly pass secrets to step (alternative to job-level env)
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: execution-logs
        path: |
          *.log
          outputs/
