name: Scheduled Lead Report

on:
  schedule:
    # Runs at 11:00, 14:00, 16:00, and 18:00 IST (UTC+5:30)
    - cron: '30 5,8,10,12 * * *'  # UTC times: 05:30, 08:30, 10:30, 12:30
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
    # Add this step BEFORE running the script to verify secrets
    - name: Verify Environment Variables
      run: |
      echo "DB_HOST: ${{ secrets.DB_HOST }}"
      echo "DB_USER: ${{ secrets.DB_USER }}"
      # Repeat for other variables (values will be masked in logs)

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create log directory
      run: mkdir -p logs

    - name: Run report script
      run: python main.py > logs/execution.log 2>&1

    - name: Archive logs
      if: always()  # This ensures logs are uploaded even if script fails
      uses: actions/upload-artifact@v4
      with:
        name: execution-logs
        path: logs/
        retention-days: 5
